<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SiteController extends Controller
{
    //
    public function index()
    {
        return view('site.index');
    }

    public function comofunciona()
    {
        return view('site.comofunciona');
    }

    public function combos()
    {
        return view('site.combos');
    }
    
    public function midia()
    {
        return view('site.midia');
    }    
    
    public function contato()
    {
        return view('site.contato');
    } 

    public function produtos()
    {
        $caldos = array(
            array(
                'id' => '1',
                'titulo' => 'Caldo <br />Verde',
                'price' => 'R$14,00',
                'image' =>'caldoverde.png',
                'description' => 'Couve com batata.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '159',
                'srowb' => 'Kcal',
                'srowc' => '8%',
                'trowa' => '33',
                'trowb' => 'Carboidrato',
                'trowc' => '6%',
                'fhrowa' => '4',
                'fhrowb' => 'Proteína',
                'fhrowc' => '0,8%',
                'fvrowa' => '1,25',
                'fvrowb' => 'Lipídio',
                'fvrowc' => '0,5%',
                'sxrowa' => '11mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '0,45%'
                    ),
            array(
                'id' => '2',
                'titulo' => 'Canja <br />de Galinha',
                'price' => 'R$14,00',
                'image' =>'canjadegalinha.png',
                'description' => 'Frango, arroz e legumes.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '245',
                'srowb' => 'Kcal',
                'srowc' => '12%',
                'trowa' => '51',
                'trowb' => 'Carboidrato',
                'trowc' => '10,2%',
                'fhrowa' => '6',
                'fhrowb' => 'Proteína',
                'fhrowc' => '1,2%',
                'fvrowa' => '1,91',
                'fvrowb' => 'Lipídio',
                'fvrowc' => '0,8%',
                'sxrowa' => '35mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '1,5%'
                ),
            array(
                'id' => '3',
                'titulo' => 'Caldo de Mandioquinha <br />com Carne',
                'price' => 'R$14,00',
                'image' =>'caldomandioquinha.png',
                'description' => 'Mandioquinha com carne.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '402',
                'srowb' => 'Kcal',
                'srowc' => '20%',
                'trowa' => '65',
                'trowb' => 'Carboidrato',
                'trowc' => '13%',
                'fhrowa' => '20',
                'fhrowb' => 'Proteína',
                'fhrowc' => '4%',
                'fvrowa' => '6,9',
                'fvrowb' => 'Lipídio',
                'fvrowc' => '3%',
                'sxrowa' => '11mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '5%'
                ),
            array(
                'id' => '4',
                'titulo' => 'Abóbora <br />Detox',
                'price' => 'R$14,00',
                'image' =>'aboboradetox.png',
                'description' => 'Abóbora e gengibre.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '139',
                'srowb' => 'Kcal',
                'srowc' => '7%',
                'trowa' => '25',
                'trowb' => 'Carboidrato',
                'trowc' => '5%',
                'fhrowa' => '3,5',
                'fhrowb' => 'Proteína',
                'fhrowc' => '0,7%',
                'fvrowa' => '2,8',
                'fvrowb' => 'Lipídio',
                'fvrowc' => '1,3%',
                'sxrowa' => '10mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '0,4%'
                ),
            array(
                'id' => '5',
                'titulo' => 'Caldo <br />de Brócolis',
                'price' => 'R$14,00',
                'image' =>'caldobrocolis.png',
                'description' => 'Brócolis e couve',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '92,8',
                'srowb' => 'Kcal',
                'srowc' => '5%',
                'trowa' => '12,7',
                'trowb' => 'Carboidrato',
                'trowc' => '2,5%',
                'fhrowa' => '6',
                'fhrowb' => 'Proteína',
                'fhrowc' => '1,2%',
                'fvrowa' => '2',
                'fvrowb' => 'Lipídio',
                'fvrowc' => '0,9%',
                'sxrowa' => '58mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '2%'
                ),
            array(
                'id' => '6',
                'titulo' => 'Sopa Legumes <br />com Carne',
                'price' => 'R$14,00',
                'image' =>'sopalegcarne.png',
                'description' => 'Sopa de legumes com carne.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '245',
                'srowb' => 'Kcal',
                'srowc' => '12%',
                'trowa' => '51',
                'trowb' => 'Carboidrato',
                'trowc' => '10,2%',
                'fhrowa' => '6',
                'fhrowb' => 'Proteína',
                'fhrowc' => '1,2%',
                'fvrowa' => '1,91',
                'fvrowb' => 'Lipídio',
                'fvrowc' => '0,8%',
                'sxrowa' => '35mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '1,5%'
                ),
            array(
                'id' => '7',
                'titulo' => 'Sopa Legumes <br />com Frango',
                'price' => 'R$14,00',
                'image' =>'sopalegfrango.png',
                'description' => 'Sopa de legumes com frango.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '245',
                'srowb' => 'Kcal',
                'srowc' => '12%',
                'trowa' => '51',
                'trowb' => 'Carboidrato',
                'trowc' => '10,2%',
                'fhrowa' => '6',
                'fhrowb' => 'Proteína',
                'fhrowc' => '1,2%',
                'fvrowa' => '1,91',
                'fvrowb' => 'Lipídio',
                'fvrowc' => '0,8%',
                'sxrowa' => '35mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '1,5%'
                )
            );
        $fitness = array(
            array(
                'id' => '8',
                'titulo' => 'Frango Grelhado <br />com Legumes',
                'price' => 'R$14,50',
                'image' =>'frangogrel.png',
                'description' => 'Peito de frango, brócolis e cenoura, sal light e especiarias.',
                'gluten' => 'false',
                'lactose' => 'true',
                'frowa' => '250g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '272',
                'srowb' => 'Kcal',
                'srowc' => '13%',
                'trowa' => '9g',
                'trowb' => 'Carboidrato',
                'trowc' => '3%',
                'fhrowa' => '50g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '67%',
                'fvrowa' => '4g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '7%',
                'sxrowa' => '117mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '5%'
                ),
            array(
                'id' => '9',
                'titulo' => 'Frango Desfiado com Batata Doce',
                'price' => 'R$14,50',
                'image' =>'frangodesf.png',
                'description' => 'Peito de frango desfiado 150g, purê de batata doce 100g, sal light e especiarias.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '250g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '326',
                'srowb' => 'Kcal',
                'srowc' => '16%',
                'trowa' => '27g',
                'trowb' => 'Carboidrato',
                'trowc' => '9%',
                'fhrowa' => '46g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '62%',
                'fvrowa' => '3g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '7%',
                'sxrowa' => '69mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '7%'
                ),
            array(
                'id' => '10',
                'titulo' => 'Frango Desfiado c/ Arroz Integral e Legumes',
                'price' => 'R$14,50',
                'image' =>'frangodesfarr.png',
                'description' => 'Peito de frango desfiado 150g, arroz integral, brócolis e cenoura 100g, sal light e especiarias.',
                'gluten' => 'false',
                'lactose' => 'true',
                'frowa' => '250g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '321',
                'srowb' => 'Kcal',
                'srowc' => '16%',
                'trowa' => '23g',
                'trowb' => 'Carboidrato',
                'trowc' => '7%',
                'fhrowa' => '47g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '63%',
                'fvrowa' => '4g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '7%',
                'sxrowa' => '81mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '3%'
                ),
            array(
                'id' => '11',
                'titulo' => 'Patinho c/ Arroz Integral e Legumes',
                'price' => 'R$15,50',
                'image' =>'patinhoarroz.png',
                'description' => 'Patinho moído 150g, arroz integral, brócolis e cenoura 100g, sal light e especiarias.',
                'gluten' => 'false',
                'lactose' => 'true',
                'frowa' => '250g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '288',
                'srowb' => 'Kcal',
                'srowc' => '14%',
                'trowa' => '23g',
                'trowb' => 'Carboidrato',
                'trowc' => '7%',
                'fhrowa' => '33g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '44%',
                'fvrowa' => '7g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '13%',
                'sxrowa' => '80mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '3%'
                ),
            array(
                'id' => '12',
                'titulo' => 'Patinho com <br />Batata Doce',
                'price' => 'R$15,50',
                'image' =>'patinhobatata.png',
                'description' => 'Patinho moído 150g, purê de batata doce 100g, sal light e especiarias.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '250g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '293',
                'srowb' => 'Kcal',
                'srowc' => '14%',
                'trowa' => '27g',
                'trowb' => 'Carboidrato',
                'trowc' => '9%',
                'fhrowa' => '31g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '42%',
                'fvrowa' => '6g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '11%',
                'sxrowa' => '68mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '3%'
                ),
            array(
                'id' => '13',
                'titulo' => 'Filé Mignon Grelhado <br />com Legumes',
                'price' => 'R$20,00',
                'image' =>'filemignon.png',
                'description' => 'Filé mignon grelhado com brócolis e cenoura.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '250g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '376',
                'srowb' => 'Kcal',
                'srowc' => '13%',
                'trowa' => '9g',
                'trowb' => 'Carboidrato',
                'trowc' => '3%',
                'fhrowa' => '44g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '67%',
                'fvrowa' => '18g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '7%',
                'sxrowa' => '117mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '5%'
                ),
            array(
                'id' => '14',
                'titulo' => 'Nhoque de <br />Batata Doce',
                'price' => 'R$18,50',
                'image' =>'nhoquebatata.png',
                'description' => 'Batata doce, amido de milho, patinho moído, molho de tomate light, sal light e especiarias',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '400g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '537',
                'srowb' => 'Kcal',
                'srowc' => '25,5%',
                'trowa' => '89g',
                'trowb' => 'Carboidrato',
                'trowc' => '18%',
                'fhrowa' => '25g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '11%',
                'fvrowa' => '9g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '4%',
                'sxrowa' => '200mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '10%'
                ),
            array(
                'id' => '15',
                'titulo' => 'Macarrão Integral <br />com Carne Desfiada',
                'price' => 'R$18,50',
                'image' =>'macarraoint.png',
                'description' => 'Macarrão Integral, patinho desfiado, molho de tomate light, sal light e especiarias',
                'gluten' => 'true',
                'lactose' => 'true',
                'frowa' => '400g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '494',
                'srowb' => 'Kcal',
                'srowc' => '23,8%',
                'trowa' => '77g',
                'trowb' => 'Carboidrato',
                'trowc' => '15%',
                'fhrowa' => '28,5g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '6%',
                'fvrowa' => '8g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '4%',
                'sxrowa' => '219mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '10,5%'
                )
            );
        $premium = array(
            array(
                'id' => '16',
                'titulo' => 'Salmão com <br />Molho de Maracujá',
                'price' => 'R$24,99',
                'image' =>'salmao.png',
                'description' => 'Salmão com molho de maracujá, arroz integral, brocólis e cenoura.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '462',
                'srowb' => 'Kcal',
                'srowc' => '23%',
                'trowa' => '45g',
                'trowb' => 'Carboidrato',
                'trowc' => '9%',
                'fhrowa' => '40g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '8%',
                'fvrowa' => '10g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '4,5%',
                'sxrowa' => '167mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '8%'
                ),
            array(
                'id' => '17',
                'titulo' => 'Filé Mignon <br />ao Molho Mostarda',
                'price' => 'R$24,00',
                'image' =>'filemignonmostarda.png',
                'description' => 'Filé mignon com molho de mostarda, arroz integral 7 grãos e brócolis.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '570',
                'srowb' => 'Kcal',
                'srowc' => '28%',
                'trowa' => '45g',
                'trowb' => 'Carboidrato',
                'trowc' => '9%',
                'fhrowa' => '56g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '11%',
                'fvrowa' => '18g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '8%',
                'sxrowa' => '200mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '10%'
                ),
            array(
                'id' => '18',
                'titulo' => 'Strogonoff <br />de Frango Funcional',
                'price' => 'R$19,00',
                'image' =>'strogonoffrangofuncional.png',
                'description' => 'Strogonoff de frango funcional, arroz integral e cenoura.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '655',
                'srowb' => 'Kcal',
                'srowc' => '32%',
                'trowa' => '41g',
                'trowb' => 'Carboidrato',
                'trowc' => '8%',
                'fhrowa' => '76g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '15%',
                'fvrowa' => '20g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '9%',
                'sxrowa' => '203mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '10%'
                ),
            array(
                'id' => '19',
                'titulo' => 'Filé de Saint Petter <br />ao Leite de Coco',
                'price' => 'R$22,00',
                'image' =>'filesaintpepper.png',
                'description' => 'Filé de Saint Petter ao Leite de Coco com pure de cabotia e couve-flor com brocólis.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '280',
                'srowb' => 'Kcal',
                'srowc' => '14%',
                'trowa' => '18g',
                'trowb' => 'Carboidrato',
                'trowc' => '3%',
                'fhrowa' => '34g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '7%',
                'fvrowa' => '8g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '9%',
                'sxrowa' => '168mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '10%'
                ),
            array(
                'id' => '20',
                'titulo' => 'Escalope de Mignon <br />ao Molho de Ervilhas',
                'price' => 'R$24,00',
                'image' =>'escalope.png',
                'description' => 'Escalope de Mignon ao molho de ervilhas com grão de bico e couver-flor com cenoura.',
                'gluten' => 'false',
                'lactose' => 'false',
                'frowa' => '350g',
                'frowb' => '',
                'frowc' => 'VD',
                'srowa' => '457',
                'srowb' => 'Kcal',
                'srowc' => '25%',
                'trowa' => '17g',
                'trowb' => 'Carboidrato',
                'trowc' => '3%',
                'fhrowa' => '50g',
                'fhrowb' => 'Proteína',
                'fhrowc' => '19%',
                'fvrowa' => '21g',
                'fvrowb' => 'Gorduras Totais',
                'fvrowc' => '9%',
                'sxrowa' => '127mg',
                'sxrowb' => 'Sódio',
                'sxrowc' => '10%'
                ),
            );        
        return view('site.produtos', compact('caldos', 'fitness', 'premium'));
    }
}
